#ifndef VRETURNSTATUS_H_
#define VRETURNSTATUS_H_


/******************************************************************************
Enum                : ReturnStatus
Description         : return status of function means function executed
                      successfully or not,any kind of error or warning
                      is there or not.
 ******************************************************************************/
typedef enum return_status
{
	SUCCESS = 0,
	VA_SUCCESS = 0,

	// Va engine related
	VA_WARNING								= 1,
	VA_ERROR 								= 2,
	VA_NULLPOINTER 							= 3,
	NULLPOINTER								= 3,
	VA_SIZEMISMATCH 						= 4,
	SIZEMISMATCH							= 4,
	VA_PARSINGFAILED 						= 5,
	PARSINGFAILED							= 5,
	VA_WRONGFORMAT 							= 6,
	WRONGFORMAT								= 6,
	VA_OUTOFBOUND 							= 7,
	OUTOFBOUND								= 7,
	VA_INVALIDVALUE 						= 8,
	INVALIDVALUE							= 8,
	VA_LOWBUFFERSIZE 						= 9,
	LOWBUFFERSIZE							= 9,
	VA_DATAYETNOTPREPARED 					= 10,
	DATAYETNOTPREPARED						= 10,
	VA_LIBRARYYETNOTINITIALIZED 			= 11,
	LIBRARYYETNOTINITIALIZED				= 11,
	VA_LIBRARYALREADYINITIALIZED 			= 12,
	LIBRARYALREADYINITIALIZED				= 12,
	VA_IMPROPERCALL 						= 13,
	IMPROPERCALL							= 13,
	VA_DUPLICATEID	 						= 14,
	DUPLICATEID								= 14,
	VA_INVALIDID 							= 15,
	INVALIDID								= 15,
	VA_VALUENOTASSIGNED 					= 16,
	VALUENOTASSIGNED						= 16,
	VA_INVALIDTIMESTAMP						= 17,
	INVALIDTIMESTAMP						= 17,
	BACKDATEDTIMESTAMP						= 17,
	VA_CALLIGNORED							= 18,
	CALLIGNORED								= 18,
	VA_IGNORE								= 19,
	VA_LIBRARYRESET							= 20,
	LIBRARYRESET							= 20,
	VA_INVALIDRESULT						= 21,
	INVALIDRESULT							= 21,
	VA_LOWRESOLUTION						= 22,

	VA_UNSUPPORTED							= 23,
	VA_TASK_WORKING							= 24,

	VA_LIBRARY_LOAD_FAIL					= 25,


	VA_PARAMETERNOTEXIST 					= 30,
	PARAMETERNOTEXIST						= 30,
	VA_PARAMETEROUTOFBOUND 					= 31,
	PARAMETEROUTOFBOUND						= 31,
	VA_PARAMETERNOTEDITABLE 				= 32,
	PARAMETERNOTEDITABLE					= 32,
	VA_INVALIDPARAMETERVALUE 				= 33,
	INVALIDPARAMETERVALUE					= 33,
	VA_WRONGPARAMETERSTRINGFORMAT 			= 34,
	VA_MANDATORYPARAMETERSYETNOTSET 		= 35,
	MANDATORYPARAMETERSYETNOTSET			= 35,
	VA_INSUFFICIENTPARAMETERS 				= 36,
	VA_NULLPARAMETER 						= 37,
	VA_PARAMETERNOTSENT 					= 38,
	VA_PARAMETERRECEIVEDSUCCESSFULLY 		= 39,
	VA_PARAMETERSPARTIALLYACCEPTED 			= 40,
	VA_INCOMPATIBLEPARAMETERS 				= 41,
	INCOMPATIBLEPARAMETERS					= 41,
	VA_PARAMETERMULTIPLEDEFINITION 			= 42,

	VA_INVALIDCOORDINATES 					= 55,
	VA_INVALIDOPERATION 					= 56,
	VA_INVALIDGRAPHICSTYPE 					= 57,
	VA_TOOMANYOBJECTS 						= 58,
	VA_INVALIDTOTALCONTROLPARAMETERS 		= 59,

	VA_MEMORYOVERFLOW 						= 70,
	MEMORYOVERFLOW							= 70,
	MEMORYOVERFLOW1							= 70,
	VA_MEMORYNOTALLOCATED					= 71,
	MEMORYNOTALLOCATED						= 71,
	VA_MEMORYALREADYALLOCATED				= 72,
	MEMORYALREADYALLOCATED					= 72,

	VA_CHANNELNOTEXIST 						= 80,
	CHANNELNOTEXIST							= 80,
	VA_DUPLICATECHANNEL 					= 81,
	DUPLICATECHANNEL						= 81,
	VA_CHANNELOVERFLOW 						= 82,
	VA_JOB_NOT_EXIST						= 83,
	CHANNELDISABLE							= 83,

	VA_TRYAGAIN 							= 100,
	VA_WAIT 								= 101,
	VA_BUSY 								= 102,

	VA_EVALUATION_PERIOD_OVER 				= 150,
	VA_CONTINUOUS_EVALUATION_OVER 			= 151,
	VA_SYSTEM_FILE_CORRUPTED 				= 152,
	VA_INVALID_HARDWARE 					= 153,
	VA_VALIDITY_EXPIRED 					= 154,
	VA_SYS_DATE_ELAPSED 					= 155,
	VA_BEYOND_INS							= 156,
	VA_NO_AVAI_LINS 						= 157,
	VA_LICENSE_CHECK_FAILED 				= 158,
	LICENSE_CHECK_FAILED					= 158,
	VA_DEMO_LICENSE_CREATE,

	VA_CAMERA_TAMPER						= 170,

	VA_UNABLETOOPENFILE						= 200,
	UNABLETOOPENFILE						= 200,

	VA_FATAL_ERROR							= 250,

	CALL_NOT_IMPLEMENTED					= 999,

	// Database related
	DB_CONNECTION_ERROR 					= 1000,
	DB_STATEMENT_ERROR 						= 1001,
	DB_UNKNOWN_ERROR 						= 1002,

	// USER RELATED
	USER_ALREADY_LOGED_IN					= 1100,
	USER_INVALID_USERNAME_PASSWORD			= 1101,
	USER_INVALID_SESSION					= 1102,
	USER_PERMISSION_DENIED					= 1103,
	USER_DETAILS_NOT_AVAILABLE	            = 1104,
	USER_INVALID_PROFILE_AUTHENTICATION		= 1105,
	USER_PENDING_MESSAGE 					= 1106,
	USER_INVALID_CLIENT_MACHINE             = 1107,

	// PTZ CONTROL
	PTZ_TOO_MANY_REQUEST 					= 1200,
	PTZ_SESSION_OCCUPIED					= 1201,
	CAMERA_DRIVER_NOT_AVAILABLE             = 1202,
	CAMERA_PARAMETER_NOT_SUPPORTED          = 1203,

	// channel
	CHANNEL_NOT_AVAILABLE        			= 1300,



	// Recording details
	RECORDING_PROFILE_NOT_AVAILABLE        = 1400,

	STORAGE_SERCHING_NOT_COMPLETED 		   = 1450,
	STORAGE_NOT_AVAILABLE                  = 1451,
	STORAGE_LOW				               = 1452,

	SSC_NULL_OBJECT_REQUEST                = 1500,
	SSC_ARGUMENT_MISMATCH                  = 1501,
	SSC_TRUNCATED_OBJ_BYTES                = 1502,
	SSC_INVALID_REQUEST_ID                 = 1503,
	SSC_CONNECTION_ERROR                   = 1504,
	SSC_SENDING_REQUEST_ERROR              = 1505,
	SSC_ACCESS_RESPONSE_ERROR			   = 1506,
	SSC_SERIALIZABLE_ERROR                 = 1507,
	SSC_FILE_NOT_FOUND                     = 1508,
	SSC_FILE_SIZE_OUT_OF_BOUND             = 1509,
	VA_CONNECTION_ERROR                    = 1510,
	VA_REQUEST_ERROR                       = 1511,
	VA_RESPONSE_ERROR                      = 1512,


	STREAMING_INVALID_REQUEST              = 1550,
	STREAMING_INVALID_SESSION              = 1551,
	STREAMING_INVALID_REQUEST_FORMAT       = 1552,


	RECORD_NOT_AVAILABLE                  = 1600,
	MATRIX_SIZE_MISMATCH                  = 1601,

	LICENSE_CHANNEL_OVER                  = 1700,
	LICENSE_USER_OVER                     = 1701,
	LICENSE_TIME_OVER                     = 1702,
	WATCHDOG_CONNECTION_ERROR             = 1703,
	WATCHDOG_RESPONSE_ERROR               = 1704,

	VAS_FACE_NO_FACE_FOUND				  = 1801,
	VAS_FACE_NO_MATCH_FOUND				  = 1802,

	// Component / Channel registration related
	//CR_REGISTRATION_SUCCESS_ADD = 1200,
	//CR_REGISTRATION_SUCCESS_DELETE,
	//CR_REGISTRATION_SUCCESS_UPDATE,
	//CR_NOT_YET_REGISTERED,

	//CR_INVALID_REQUEST = 1210,
	//CR_INVALID_SIGNATURE,
	//CR_UNKNOWN_COMPONENT,
	//CR_UNKNOWN_PARAMETER,
	//CR_MISSING_ARGUMENT,
	//CR_TOO_LONG_PARAMETER_VALUE,
	//CR_INVALID_REQUEST_FORMAT,
	// CR_INVALID_COMPONENT_ID,
	//
	// CR_REQ_COMPONENT_TYPE = 1230,
	// CR_REQ_COMPONENT_ID, 					
	// CR_REQ_COMPONENT_NAME, 					
	// CR_REQ_COMPONENT_URL, 					
	// CR_REQ_COMPONENT_SIGNATURE, 			
	// CR_REQ_COMPONENT_TIMESTAMP, 			

	// Vas_Controller_Related

	//VSC_CHANNEL_ADDED_SUCCESSFULLY	= 1300,
	//VSC_CHANNEL_REMOVED_SUCCESSFULLY,
	//VSC_RESULT_NOT_AVALIABLE,
	//VSC_UNKNOWN_SERVER_ENDIAN,
	//VSC_CHANNEL_NOT_PRESENT,
	//VSC_UNKNOWN_APPLICATION,

	//VSC_CONNECTION_ERROR,
	//VSC_SENDING_REQUEST_ERROR,
	//VSC_ACCESS_RESPONSE_ERROR,

	//VSC_ALREADY_IN_PAUSE = 1315,
	//VSC_ALREADY_IN_RESUME,


	// Network
	NW_CONNECTION_ERROR = 2000,
	NW_READING_FAILED,
	NW_WRITING_FAILED,
	NW_TOO_MANY_CONNECTION,
	NW_SOCK_CREATE_FAIL,
	NW_BIND_FAIL,
	NW_LISTEN_FAIL,
	NW_SERVER_ACCEPT_FAIL,
	NW_TIMEOUT,

	DB_EC_CONNECTION_FAILED = 3000,
	DB_EC_QUERY_FAILED,

	FILE_OPEN_FAILED = 4000,
	FILE_REMOVE_FAILED,
	FILE_WRITE_FAILED,
	FILE_READ_FAILED,
	FILE_ALREADY_OPENED,
	END_OF_FILE,

	VA_DECODER_ALREADY_CLOSED = -7,
	VA_DECODER_CRITICAL_ERROR = -22,

	VDEVICE_INVALID_STREAM_TYPE = 3504,
	VDEVICE_INVALID_CODEC_TYPE = 3505,
	VDEVICE_INVALID_WIDTH = 3506,
	VDEVICE_INVALID_HEIGHT = 3507,
	VDEVICE_INVALID_IP_RATE = 3508,
	VDEVICE_INVALID_BIT_RATE_MODE = 3509,
	VDEVICE_INVALID_FPS = 3510,
	VDEVICE_INVALID_BITRATE = 3511,
	VDEVICE_INVALID_BRIGHTNESS = 3512,
	VDEVICE_INVALID_CONTRAST = 3513,
	VDEVICE_INVALID_HUE = 3514,
	VDEVICE_INVALID_IRIS_MODE = 3515,
	VDEVICE_INVALID_SATURATION = 3516,
	VDEVICE_INVALID_RESOLUTION = 3517

} ReturnStatus;

typedef ReturnStatus VReturnStatus;

#endif /*VRETURNSTATUS_H_*/
